spring:
  application.name: spring-batch-demo
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
    schema: classpath:schema.sql
    data: classpath:data.sql
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
      platform: h2 # Spring Boot >=v2.5.0
  h2:
    console.enabled: true



